language: node_js
sudo: false
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  global:
  - secure: ACD2rzQ1p9Du71KEaeEKIgBx/mOmK5iFuTOP0ctcS5LjgrhTbtIoIlYMId3gljwd/zBpvzUpoOpavNdBGIpPrfw0pGhBMvVfIO971z+NcOvj8fsX8qm6RPXvhnM1zyMU/GeG0FOq99sQTOsFRtLhYXGYyz9B7bqsBD1G4jCsTsH+tis2Qrr1Zy3zIn5MxBMJzYBZEY5gHd5zs25JZ7yr5vvGmlGRL8Z/74AZv3fgGcsVasxNMa+wdwv8SGqR6qMEY9UeGW02u+DVO+dna+E4D1DUPu+B3NTk+04xgxqGiBTCUOgKQhbzID6LLmA08GNKT2r1BbiMl4OeDKis2sbNYfEcoHPfDZDOT6vs4W8iIBxJU8Da1IIJqj6YpNhaeqfteGki4FV4RwYfVknCM18lnrPiU0emHKGlYuIg8ZA1F8RfJEcvJ34cY9ELbPhq00OcvsT8YYDLU3r/9PdSxFbqcQycsMOWmdOroytrjjFThciFJhMXtq10mg0zhOenRAnmPYi7M5vLn67smilaH+BWTpm/3g4th8ykhi+jAgIOew9P3wvbMb5iehO7plvEQorAqKtAnWw7Km0eyjQObk+1nTlm+BVXhXSqcR6XKt6eb3CQaMvWeWpBG/BxUmrfYWhqwtixeFtJ3JQgbtAGkrdgV2wfQq/Mw08OduCKAa2qk6c=
  - secure: hgtg/cnSoznPcqnkdI7InVFhVg7ASMdgqjUTg0bK0eoUAM7I0t1jMfxc7ZEgvcFpVHhn11YZngKA/vR6WyznIh2G82mKGUKLXAI1k2+eg2pzgFXY1JNB7xocI9V2ZES4zwsxE34vs8pXCpOqtdOeYUvduSColjnFMx5TEqRVn7JunXnAMUwACfAqe6HlTXUXD/mWSaenBlPyt02GAq9MEiFZ8BRhj6/utfOxkFP/Defajbi4fNY/vHqkkL8m+GUZWeP31XsVrxRQm/rSdJnG0rXrTpMxp7bB/qTV37PkjDjJabuw0saPeT5Agr+fLMRa983rowo2snDj10VSFFqkhReWj8S4uf5kJS6d7NMDz4DW2VXCQnzcUhRXeXr1otVYjbHgCEy4TIog6g8ep1Gqg4svwvvqA7sa7Q1VBYQi7XKZVjugE5qz+1BQTFBBUw+8ZAYkQJvmto3VFB+BVy2XkxxUtPEY9KftlKCPo2G4jBybUS99UBwSLleyJ2cG+kXOtkUfXFFbV4fQMZ96EYHg7LGa/lCmnkS0zTPoDvyjVCVBrnssO5VLQQXirZpt3jhaxzffQXbtwoONxTmPWWm8Hv8w5pd4MW0uiCzkd1f2xfYIVw2y4cjQlTKFVDKM/z2Lc7Uy020dtZvBEBzzdlOsuIekHrcUGysbY7TMErREsJ4=
  matrix:
  - BROWSER=PhantomJS npm_config_coverage=true
  - BROWSER=SL_Chrome
  - BROWSER=SL_Firefox
  - BROWSER=SL_Safari
  - BROWSER=SL_IE_8
  - BROWSER=SL_IE_9
  - BROWSER=SL_IE_10
  - BROWSER=SL_IE_11
